Addressing Review Comments - Part 5
harshit7962/wpf pull request #23
Opened 2024-03-27 05:51 UTC by dipeshmsft

Fixes # 

Main PR 

## Description

## Customer Impact

## Regression

## Testing

## Risk

2024-03-27 10:21 UTC, harshit7962 requested changes

2024-03-27 12:07 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
> +            return _DwmSetWindowAttribute(hwnd, DWMWA.SYSTEMBACKDROP_TYPE, ref dwmWindowAttribute, sizeof(int));
I was matching the pattern earlier, but I will look into it.

2024-03-27 12:08 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Interop/UnsafeNativeMethodsWindow.cs
> -        if (backdropPvAttribute == (int)Standard.DWMSBT.DWMSBT_NONE)
Yes, it is thought of, this allows us to fix transition from Mica -> None

2024-03-27 12:23 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/WindowBackdropType.cs
> +    Auto,
Removed the comments at once.

2024-03-27 12:23 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/EditingCommands.cs
> +        internal static RoutedUICommand Clear { get { return EnsureCommand(ref _Clear, "Clear"); }}
Fixed

2024-03-27 12:23 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/DWMColorization.cs
> +        return systemAccentByteValue;
Renamed.

2024-03-27 12:48 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Standard/NativeMethods.cs
> +            return _DwmSetWindowAttribute(hwnd, DWMWA.SYSTEMBACKDROP_TYPE, ref dwmWindowAttribute, sizeof(int));
I have fixed this.

2024-03-28 05:30 UTC, harshit7962 approved these changes

2024-03-28 10:43 UTC, merged