Slider accent color and ticks fix
harshit7962/wpf pull request #26
Opened 2024-04-08 08:42 UTC by dipeshmsft

Fixes # 

Main PR 

## Description

## Customer Impact

## Regression

## Testing

## Risk

2024-04-08 12:03 UTC, harshit7962 commented
Due to these changes mouse over effect is discarded.

2024-04-08 12:04 UTC, harshit7962 requested changes

2024-04-08 12:13 UTC, dipeshmsft commented on src/Microsoft.DotNet.Wpf/src/Themes/PresentationFramework.FluentWindows/Styles/Slider.xaml
> +                        Background="{DynamicResource SliderOuterThumbBackground}"
Matching how WinUI does it.

2024-04-09 09:10 UTC, dipeshmsft commented
I have added animation instead for feedback. Similar to how WinUI does it.

2024-04-09 12:17 UTC, harshit7962 approved these changes
Verified the changes in sample application, the visual feedback on pressed and mouse over is appropriate.

2024-04-09 14:08 UTC, merged